### ISSUE TITLE
Not interested programming language news are listed

### ISSUE THREAD

**Issue by mk48** [medyo/hackertab.dev#155]
I never included Python in the interested list but Python news are listed.
![image](https://github.com/medyo/hackertab.dev/assets/3082469/67f2d6ac-faaa-453b-893a-8fb12b9874a6)

**Comment by medyo** [comment]
The reason is that you're showing the trending content from dev.to, which presents popular content regardless of the selected tags. You can selected `My languages` to keep only the content of your followed tags.

![image](https://github.com/medyo/hackertab.dev/assets/2389584/22125539-5a79-40c8-bc66-608b18a653c4)

**Comment by mk48** [comment]
Thanks 👍
