### ISSUE TITLE
[Feature] Add TechCrunch data (requires adding functionality to API to parse RSS feed into JSON)

### ISSUE THREAD

**Issue by ScottGrun** [medyo/hackertab.dev#24]
Just a thought, could you add a Techcrunch endpoint to your API so you can have a TechCrunch card? Looks like they have a bunch of RSS feeds that you could parse into JSON and send back to the client. The different feeds (Gadgets, Mobile. Startups, etc) could also be different options for the cards. I was able to get a demo working locally that hits one of the feeds listed at https://techcrunch.com/pages/rssfeeds/feed/ and then uses the xml2js package(https://www.npmjs.com/package/xml2js) to convert the returned XML into JSON.  Supporting RSS feeds could also possibly opening up this extension to a bunch more possible data sources.

**Comment by medyo** [comment]
Actually, Hackertab is more **"developer"** oriented where we break down (tools, jobs, news...) by programming language.
I'm not sure TechCrunch would be a good fit for Hackertab since it's an online newspaper focusing on startups and companies.
Still, I'd appreciate hearing more comments on the matter. If users show interest, I may reconsider adding it (in certain ways).
