### ISSUE TITLE
Manifest warning: icons property ignored

### ISSUE THREAD

**Issue by andypiper** [medyo/hackertab.dev#80]
JS console shows:

`Manifest: property 'icons' ignored, type array expected.`

**Comment by medyo** [comment]
That's really confusing, the `icons` object is defined correctly as the documentation says:
https://developer.chrome.com/docs/extensions/mv2/manifest/icons/
However this warning is showing, I'll give it another try later

**Comment by malcolmocean** [comment]
I solved this in an unrelated project: the issue is that the Chrome Extension manifest.json is getting referenced as a Web Application manifest.json, which DOES want `icons` as an array. The solution is to remove whatever line looks like this:

```
 <link rel="manifest" href="manifest.json" />
```

Or, alternatively, to make a separate web_manifest.json file now with the appropriate icons array.

I see that your project has already solved this, so I'm leaving this comment for the benefit of anyone who arrives via google, as I did while trying to solve the issue in my own extension.
